In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

PCA example

In [5]:
x = [2,3,4,5,6]
y = [4,6,8,10,12]
z = [8,12,16,20,24]
# x = [2,3,4,5]
# y = [4,6,8,10]
zero_shift = np.stack((x-np.sum(x)/len(x),y-np.sum(y)/len(y),z-np.sum(z)/len(z)), axis=0)
print("zero_shift: \n",zero_shift)
mat = np.stack((x, y, z), axis = 0)
mat = np.array(mat)
cov = np.cov(mat,bias=True)
print("cov: \n",cov)
vals,vecs = np.linalg.eig(cov)
print("eigenvals: \n",vals[::-1])
vecs = np.transpose(vecs)
print("eigenvecs: \n",(vecs[0])/max(vecs[0]),(vecs[1])/max(vecs[1]),(vecs[2])/max(vecs[2]))


zero_shift: 
 [[-2. -1.  0.  1.  2.]
 [-4. -2.  0.  2.  4.]
 [-8. -4.  0.  4.  8.]]
cov: 
 [[ 2.  4.  8.]
 [ 4.  8. 16.]
 [ 8. 16. 32.]]
eigenvals: 
 [ 6.77927340e-31 -1.83015402e-16  4.20000000e+01]
eigenvecs: 
 [0.25 0.5  1.  ] [ 0.44448876 -2.22224438  1.        ] [-1.73457745e-15 -2.00000000e+00  1.00000000e+00]


PCA proper